version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true

# Options for custom base configuration file
clash_rule_base = "https://raw.githubusercontent.com/zhongfly/clash-config/master/clash.yml"
#surge_rule_base = "base/surge.conf"
#surfboard_rule_base = "base/surfboard.conf"
#mellow_rule_base = "base/mellow.conf"
#quan_rule_base = "base/quan.conf"
#quanx_rule_base = "base/quanx.conf"

# Options for adding emojis
add_emoji = true
remove_old_emoji = true

# Options for filtering nodes
#include_remarks = []
exclude_remarks = ["(流量|时间|产品|免费|耗尽|到期|订阅|更新|剩余|可用|当前|卡顿)","^(官网|群组|频道)","IPv6测试节点","wuan|HKIX@Bosa"]

# 设置分组标志位
[[custom_groups]]
name = "🚀 节点选择"
type = "select"
rule = [
    "[]♻️ 自动",
    "[]🎯 全球直连",
    ".*"
]

[[custom_groups]]
name = "♻️ 自动"
type = "url-test"
rule = ["(^(?!.*(?i:\\b([6-9]|[1-9]\\d+)(\\.\\d+)?x|日本)).*)"]
url = "http://www.gstatic.com/generate_204"
interval = 60
tolerance = 50

[[custom_groups]]
name = "🤖 AI"
type = "select"
rule = [
    "[]♻️ 境外",
    "[]♻️ 自动",
    "[]🚀 节点选择",
    ".*"
]

[[custom_groups]]
name = "📖 漫画"
type = "select"
rule = [
    "[]✴️ 负载均衡",
    "[]🚀 节点选择",
    "[]🎯 全球直连",
    "(^(?!.*(?i:JP|Japan|Tokyo|Osaka|Saitama|日本|东京|大阪|埼玉|[^-]日)).*)"
]

[[custom_groups]]
name = "✴️ 负载均衡"
type = "load-balance"
rule = ["(^(?!.*(?i:JP|Japan|Tokyo|Osaka|Saitama|日本|东京|大阪|埼玉|[^-]日)).*)"]
interval = 60
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "♻️ 境外"
type = "load-balance"
rule = ["(^(?!.*(?i:HK|香港|MO|澳门|\\b([4-9]|[1-9]\\d+)(\\.\\d+)?x)).*)"]
url = "http://www.gstatic.com/generate_204"
interval = 60
strategy = "sticky-sessions"

[[custom_groups]]
name = "🎯 全球直连"
type = "select"
rule = ["[]DIRECT"]

[[custom_groups]]
name = "🛑 全球拦截"
type = "select"
rule = ["[]REJECT", "[]DIRECT","[]🚀 节点选择",".*"]

[[custom_groups]]
name = "🐟 漏网之鱼"
type = "select"
rule = ["[]🚀 节点选择",
"[]🎯 全球直连",
"[]♻️ 自动"]
# 设置分组标志位


# 设置规则标志位
# 个人规则
[[rulesets]]
group = "🎯 全球直连"
ruleset = "https://raw.githubusercontent.com/zhongfly/clash-config/master/Direct.yaml"
type = "clash-classic"
[[rulesets]]
group = "🚀 节点选择"
ruleset = "https://raw.githubusercontent.com/zhongfly/clash-config/master/proxy.yaml"
type = "clash-classic"
[[rulesets]]
group = "📖 漫画"
ruleset = "https://raw.githubusercontent.com/zhongfly/clash-config/master/comic.yaml"
type = "clash-classic"

[[rulesets]]
group = "🎯 全球直连"
ruleset = "[]GEOSITE,private"
# ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.yaml"
# type = "clash-domain"

# 广告拦截
[[rulesets]]
group = "🛑 全球拦截"
ruleset = "[]GEOSITE,category-ads-all"
# ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ads-all.yaml"
# type = "clash-domain"

# 类型直连
[[rulesets]]
group = "🎯 全球直连"
ruleset = "[]GEOSITE,category-games@cn"
# ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games@cn.yaml"
# type = "clash-domain"
[[rulesets]]
group = "🎯 全球直连"
ruleset = "[]GEOSITE,microsoft@cn"
# ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft@cn.yaml"
# type = "clash-domain"
[[rulesets]]
group = "🚀 节点选择"
ruleset = "[]GEOSITE,google@cn"
# ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google@cn.yaml"
# type = "clash-domain"

[[rulesets]]
group = "🤖 AI"
ruleset = "[]GEOSITE,category-ai-!cn"

# 代理
[[rulesets]]
group = "🚀 节点选择"
ruleset = "[]GEOSITE,geolocation-!cn"

# 直连
[[rulesets]]
group = "🎯 全球直连"
ruleset = "[]GEOSITE,cn"

# IP类规则
[[rulesets]]
group = "🎯 全球直连"
ruleset = "[]GEOIP,private"
# ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.yaml"
# type = "clash-ipcidr"
[[rulesets]]
group = "🚀 节点选择"
ruleset = "[]GEOIP,telegram"
# ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.yaml"
# type = "clash-ipcidr"
[[rulesets]]
group = "🎯 全球直连"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "🐟 漏网之鱼"
ruleset = "[]MATCH"
# 设置规则标志位


[[emoji]]
match = "(Australia|Sydney|澳大利亚|澳洲|悉尼)"
emoji = "🇦🇺"
[[emoji]]
match = "(Brazil|Paulo|巴西|圣保罗)"
emoji = "🇧🇷"
[[emoji]]
match = "(?i:\\bCA[N]?\\b|Canada|Toronto|Montreal|Vancouver|加拿大|蒙特利尔|温哥华|楓葉|枫叶)"
emoji = "🇨🇦"
[[emoji]]
match = "(?i:DE|Germany|法兰克福|德)"
emoji = "🇩🇪"
[[emoji]]
match = "(?i:\\bFR[A]?\\b|France|Paris|法国|巴黎)"
emoji = "🇫🇷"
[[emoji]]
match = "(?i:UK|England|United.*?Kingdom|London|英|伦敦)"
emoji = "🇬🇧"
[[emoji]]
match = "(Italy|Milan|意大利|米兰)"
emoji = "🇮🇹"
[[emoji]]
match = "(India|Mumbai|印度|孟买)"
emoji = "🇮🇳"
[[emoji]]
match = "(柬埔寨|Cambodia)"
emoji = "🇰🇭"
[[emoji]]
match = "(卢森堡|LU)"
emoji = "🇱🇺"
[[emoji]]
match = "(?i:JP|Japan|Tokyo|Osaka|Saitama|日本|东京|大阪|埼玉|[^-]日)"
emoji = "🇯🇵"
[[emoji]]
match = "(?i:KR|Korea|KOR|首尔|韩|韓)"
emoji = "🇰🇷"
[[emoji]]
match = "(Macao|澳门|CTM)"
emoji = "🇲🇴"
[[emoji]]
match = "(墨西哥|Mexico)"
emoji = "🇲🇽"
[[emoji]]
match = "(Malaysia|马来西亚)"
emoji = "🇲🇾"
[[emoji]]
match = "(?i:\\bNL[D]?\\b|Netherlands|荷兰|阿姆斯特丹)"
emoji = "🇳🇱"
[[emoji]]
match = "(Philippines|菲律宾)"
emoji = "🇵🇭"
[[emoji]]
match = "(?i:RU|Russia|Moscow|Petersburg|Siberia|伯力|莫斯科|圣彼得堡|西伯利亚|新西伯利亚|哈巴罗夫斯克|俄|毛子)"
emoji = "🇷🇺"
[[emoji]]
match = "乌克兰"
emoji = "🇺🇦"
[[emoji]]
match = "(?i:SG|Singapore|新加坡|狮城|[^-]新)"
emoji = "🇸🇬"
[[emoji]]
match = "(?i:\\bTH\\b|Thailand|泰国|曼谷|泰)"
emoji = "🇹🇭"
[[emoji]]
match = "(?i:TW|Taiwan|台湾|[^-]台)"
emoji = "🇨🇳"
[[emoji]]
match = "(?i:US|America|United.*?States|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥)"
emoji = "🇺🇸"
[[emoji]]
match = "(?i:\\bUAE\\b|Dubai|阿联酋|迪拜)"
emoji = "🇦🇪"
[[emoji]]
match = "(Argentina|阿根廷)"
emoji = "🇦🇷"
[[emoji]]
match = "(Vietnam|越南|越)"
emoji = "🇻🇳"
[[emoji]]
match = "(Turkey|土耳其|伊斯坦布尔)"
emoji = "🇹🇷"
[[emoji]]
match = "(?i:HK|Hong.*?Kong|HKT|HKBN|HGC|WTT|CMI|港)"
emoji = "🇭🇰"






